### ISSUE TITLE
question in the stat-controller.

### ISSUE THREAD

**Issue by mdreyes** [jlgraves3/food-diary#1]
your app is awesome!!!
can you explain how you did thise code
```javascript
statsController.index = (req,res) => {
	var end = "\'" + moment().add(1,'day').format('YYYY-MM-DD') + "\'" ;
	var start = "\'" + moment().subtract(7,'day').format('YYYY-MM-DD') + "\'" ;
	console.log(start,end);

	//get stats for past week
	Stats.totalCals(req.user.id,start,end).then(totalCals => {
		Stats.allCals(req.user.id,start,end)
		//initialize data
		.then(weekData => {
			let cals = [];
			let dates = [];
			weekData.forEach((i) => {
				cals.push(i.daily_sum + '');
				dates.push(i.date);
			});
		//render page/graph with data
		res.render('stats/stats-index', {
			dates: formatDates(dates),
			cals: cals,
			avgCals: totalCals[0].sum/7,
			currentPage: 'stats',
			username: req.user.username,
			months: pastYearMonths(),
		});
	});

	}).catch(err => {
		console.log(err);
		res.status(500).json({error:err});
	});
}
```
Thank you

**Comment by jlgraves3** [comment]
Thanks! This part is for my stats index page where I am showing a graph of the daily calories eaten for the past week and links to stat pages for each of the past 12 months. I didn't comment or organize this very well so I can see why it might not make sense 😆 

```javascript
statsController.index = (req,res) => {
	var end = "\'" + moment().add(1,'day').format('YYYY-MM-DD') + "\'" ;
	var start = "\'" + moment().subtract(7,'day').format('YYYY-MM-DD') + "\'" ;
	console.log(start,end);

	//get stats for past week
	Stats.totalCals(req.user.id,start,end).then(totalCals => {
		Stats.allCals(req.user.id,start,end)
```
To get the calorie data for the past week, I use a start date (7 days ago) and an end date (current day), stored in ```start``` and ```end``` variables,  to then query info from the Stats model for food diary entries that are in between those two days. ```Stats.allCals``` (badly named, should be called allDailyCals instead) gets the total calories consumed for each day between start and end date and ```Stats.totalCals``` gets the total calories consumed for the whole week. 


```javascript
                //initialize data
		.then(weekData => {
			let cals = [];
			let dates = [];
			weekData.forEach((i) => {
				cals.push(i.daily_sum + '');
				dates.push(i.date);
			});
```

```weekData``` is the data returned from ```Stats.allCals``` which is formatted like:

```
[ {date: '2017-08-07', 
   daily_sum: 2000},
  {date: '2017-08-08', 
   daily_sum: 2100}, ... ]
```
In the forEach loop I am pushing all the dates into the ```dates``` array and all the calories into the ```cals``` array from the ```weekData``` object array so that the data is formatted the way I will need for the chart.

```javascript
                //render page/graph with data
		res.render('stats/stats-index', {
			dates: formatDates(dates),
			cals: cals,
			avgCals: totalCals[0].sum/7,
			currentPage: 'stats',
			username: req.user.username,
			months: pastYearMonths(),
		});
```
In this part I am passing the ejs file the dates and cals arrays I just created (which will be rendered into a graph using chartjs). The ```avgCals``` field is the average calories consume per day that week so I am just dividing the sum of all calories that week (```totalCals```) by 7. The ```months``` field is an array of the past 12 months including the current month (which I am getting with the function ```pastYearMonths()```)

I think that's pretty much it
